### PR TITLE
Neighbour exchanges in delamination

### PR DESCRIPTION
**Pull request by btbest**
Hi Guillaume! I've finally found time to put together the modifications that I made to tyssue for my postdoc, and to submit the stuff that you might be interested to take over. I'm creating one branch for each "feature" that I added (and one with miscellaneous stuff like more detailed function descriptions). For now there's just this one and the misc_fixes branch on my fork, but I will hopefully find time next week to do the remaining two.

The changes on this branch implement a neighbour_exchanges event that allows simulations to have faces undergoing "partial" neighbour exchanges rather than stereotyped T1-transitions. I implemented this because in our model system (Chironomus riparius), mesodermal cells fluidly shift past each other, and only sometimes (by coincidence) these neighbour rearrangements are equivalent to full T1-transitions. I also added return values to all the topological change functions to make tracking, analysis and visualisations easier.

I'm creating the PR here to notify you, but I might end up stumbling upon more stuff that should go into this branch as well. I'll let you know when I think I'm done!

Feel free to discard anything you're not too happy with, or let me know any changes you'd like me to make. I'm also of course happy to answer any questions about why I did stuff the way I did, or to provide the modifications to the DamCB/invagination module that make use of this new functionality.

### CODE REVIEW

**Comment by glyg** [comment]
Hi @btbest thanks a lot for the PR - I am in a dramatic lack of spare time at the moment (I'm between 2 overlapping jobs and cities) so please don't worry if I don't review the code very soon. Hopefully things will settle a bit in January

Thanks again!

**Comment by glyg** [comment]
Hi @btbest thanks a lot, I should be able to test the code today and see if the tests pass

**Comment by btbest** [comment]
Great! The functional code changes that you see on this branch have not changed in the meantime; there wasn't anything else to add in the end

**Comment by glyg** [comment]
Hi @btbest - one of the tests is failing (an apoptosis code ) with your branch:

`FAILED behaviors/test_sheet_events.py::test_execute_apoptosis - assert 40 < 40`

It looks like a 3 sided face is not eliminated.... I don't have a lot of time today to debug this (I'm not sure @sophietheis is super free either, but she wrote the test so maybe she can have a look?)

If you have a bit of time the error is [here](https://github.com/DamCB/tyssue/blob/d55e5964c9ee0c9d601591d29ba381af8747a941/tests/behaviors/test_sheet_events.py#L181) - you can copy paste the imports and the function and run it. 

Thanks again for contributing to tyssue!

**Comment by sophietheis** [comment]
Hi, 
The face is not eliminated because when the cell has 4 sides, we were doing one last step execution, due to the fact that every 3 sides cells was automatically remove (if I remember well). The test stop the simulation when the cell has 3 sides and so it is not eliminated. You can change the while loop end condition by replacing '4' by '3' [here](https://github.com/DamCB/tyssue/blob/d55e5964c9ee0c9d601591d29ba381af8747a941/tests/behaviors/test_sheet_events.py#L170).  Test should pass with this correction.

**Comment by btbest** [comment]
Well that's a quick fix to implement, not so quick apparently for me to try to get the tests working while I have four different versions of tyssue on my system :upside_down_face:

**Comment by glyg** [comment]
I checked that the code passes the tests, thanks a lot @btbest , merging now

**Comment by glyg** [comment]
BTW I'd like to work on a 1.0 soon, to give that library some love :) Thanks again for your contribution!

**Comment by btbest** [comment]
In fact thank _you_ for accepting my very first contribution to an open-source project! ;)

All the best for 1.0 - if I manage to find some time maybe I can even contribute a little on the code-related parts of that to-do list

**Comment by glyg** [comment]
I hope it's the first of many to come (not necessarily on tyssue :wink: )

**Pull request merged**
